server.port: 8081

spring:
  application:
    name: dummy-service
  security:
    basic.enabled: false
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/auth/realms/service/protocol/openid-connect/certs